// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAd-mQguliNK1cAu6Ng7S0JPiw-h0PE-_Q',
    appId: '1:298862813372:web:194283d25353599b12f0b9',
    messagingSenderId: '298862813372',
    projectId: 'veterinaria-11f1a',
    authDomain: 'veterinaria-11f1a.firebaseapp.com',
    databaseURL: 'https://veterinaria-11f1a-default-rtdb.firebaseio.com',
    storageBucket: 'veterinaria-11f1a.appspot.com',
    measurementId: 'G-JKKF8FT2VX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAB_O-AxDcfM2kFbTrbSK6pEzoY2n3phKw',
    appId: '1:298862813372:android:5d35d5e3fc10a5bd12f0b9',
    messagingSenderId: '298862813372',
    projectId: 'veterinaria-11f1a',
    databaseURL: 'https://veterinaria-11f1a-default-rtdb.firebaseio.com',
    storageBucket: 'veterinaria-11f1a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLkU3gWlXaH5UrRyg3Nhmwmdf5JF5lR7Y',
    appId: '1:298862813372:ios:c56154d91780d64b12f0b9',
    messagingSenderId: '298862813372',
    projectId: 'veterinaria-11f1a',
    databaseURL: 'https://veterinaria-11f1a-default-rtdb.firebaseio.com',
    storageBucket: 'veterinaria-11f1a.appspot.com',
    iosClientId: '298862813372-hu2f5nrjsqk6tfd24ihish5bdsjuoodt.apps.googleusercontent.com',
    iosBundleId: 'com.histovet.histovet',
  );
}
